pipeline: 
    # build:
    #     image: hub.c.163.com/library/node:latest
    #     commands:
    #         - npm config set registry https://registry.npm.taobao.org && npm install && node server.js
    publish_push:
        image: plugins/docker:17.05
        # registry: https://hub.docker.com
        username: ljzhou5
        password: [ docker_password ]
        repo: ljzhou5/test
        tags: ${DRONE_COMMIT}
        dockerfile: Dockerfile
        when:
            event: [ push, pull-request ]
            branch: 
                - master
    deploy_prod:
        image: appleboy/drone-ssh:1.3
        host: 140.143.208.95
        username: ubuntu
        port: 22
        password: [ tencent_password ]
        script:
            - docker rm -f svg2iconfont
            - docker run -d -p 8097:8097 --name=svg2iconfont ljzhou5/test:${DRONE_COMMIT}
        when:
            event: [ push ]

